name 'lesaux-monit'
version '0.0.1'

author 'Pierig Le Saux'
license 'GPLv2'
project_page 'http://github.com/lesaux/puppet-monit'
source 'git://github.com/lesaux/puppet-monit'
summary 'Monit Module'
description 'Monit Module for Debian, RedHat'
dependency 'dhoppe/role', '>=0.0.1'
